### ISSUE TITLE
Could you tell me the where is “mxnet_detector”？

### ISSUE THREAD

**Issue by chenruolin2019** [RizhaoCai/MetaPattern_FAS#2]

**Comment by RizhaoCai** [comment]
Please check https://github.com/YYuanAnyVision/mxnet_mtcnn_face_detection

**Comment by chenruolin2019** [comment]
Ok ,thank you. But I couldn't find the "mxnet_detector.detect_and_align" function in "https://github.com/YYuanAnyVision/mxnet_mtcnn_face_detection"

**Comment by RizhaoCai** [comment]
> Ok ,thank you. But I couldn't find the "mxnet_detector.detect_and_align" function in "https://github.com/YYuanAnyVision/mxnet_mtcnn_face_detection"

I see.

Below are the contents of mxnet_detector.py I used in my machine. You can create a file named "mxnet_detector" and copy the below contents to this file.

```python
import mxnet as mx
from mtcnn_detector import MtcnnDetector
import cv2
import os
import time

detector = MtcnnDetector(model_folder='/home/rizhao/code/mxnet_mtcnn_face_detection/model', ctx=mx.cpu(0), num_worker = 8 , accurate_landmark = False)

def detect_and_align(img, desired_size=256):
    global detector
    results = detector.detect_face(img)

    total_boxes = results[0]
    points = results[1]

    # extract aligned face chips
    chips = detector.extract_image_chips(img, points, desired_size, 0.37)
    return chips[0]

```

**Comment by chenruolin2019** [comment]
Ok, thank you very much!  I'll try it soon.

**Comment by chenruolin2019** [comment]
Excuse me, I have another question: 
cannot import name 'metric_report_from_dict' from 'test'
 I couldn't find the file named "test".

**Comment by RizhaoCai** [comment]
> Excuse me, I have another question: cannot import name 'metric_report_from_dict' from 'test' I couldn't find the file named "test".

Please refer to #4
