### ISSUE TITLE
[Errno 2] No such file or directory: 'models/MetaTexFPNv6_1/net.pth'

### ISSUE THREAD

**Issue by chenruolin2019** [RizhaoCai/MetaPattern_FAS#5]
[Errno 2] No such file or directory: 'models/MetaTexFPNv6_1/net.pth' Could you provide this file?

**Comment by RizhaoCai** [comment]
Hi Ruolin @chenruolin2019 ,

Recently I have not had enough time to check all over the code, and I am sorry for the trouble made to you. 
The 'models/MetaTexFPNv6_1/net.pth'  is a pretrain model which uses imagenet pretrain backbone.
Please check the latest commit. 

Thanks for your feedback.
