### ISSUE TITLE
Could you provide me some information about your environment?

### ISSUE THREAD

**Issue by chenruolin2019** [RizhaoCai/MetaPattern_FAS#6]
For example, the version of Pytorch, cuda, python, mxnet, opencv and so on.

**Comment by chenruolin2019** [comment]
aha？

**Comment by RizhaoCai** [comment]
@chenruolin2019 

Hi, I think the implementation does not rely on specific versions of libraries.

Here is some of the information:
PyTorch 1.6
CUDA10.1
python3.6
mxnet (not sure)
opencv (not sure)
